### ISSUE TITLE
Select element doesn't work properly with native HTML form

### ISSUE THREAD

**Issue by piotretm** [siemens/ix#834] opened 2023-10-10 10:23 UTC
### What happened?

When I want to use the `ix-select` element within the form it does not work - the value is not visible in the form data. I think the issue is that it is not possible to set the property `name` which is required in [this case](https://www.w3schools.com/tags/att_input_name.asp)

### What type of frontend frameware are you seeing the problem on?

JavaScript

### Which version of iX do you use?

2.0.1

### Code to produce this issue.

```shell
https://stackblitz.com/edit/uvf1ch?file=src%2Findex.html
```

**Comment by danielleroux** [comment] 2023-10-10 10:25
Duplicate of https://github.com/siemens/ix/issues/691

**Closed by danielleroux** 2023-10-10 10:25 UTC
Labels: triage

**Comment by piotretm** [comment] 2023-10-10 10:33
@danielleroux could you help me understand why it was marked as duplicate?
