### ISSUE TITLE
"app-menu" icon not working

### ISSUE THREAD

**Issue by JulianEvi** [siemens/ix#818] opened 2023-10-09 07:39 UTC
### What happened?

The "app-menu" icon does not work in version 2.0.1 and the icon is also blank in the icon documentation. 
"folder-new" is also not shown in the documentation. Probably the same issue.

### What type of frontend frameware are you seeing the problem on?

Angular

### Which version of iX do you use?

2.0.1

### Code to produce this issue.

```shell
<ix-icon name="app-menu" size="16"></ix-icon>
```

**Comment by danielleroux** [comment] 2023-10-09 10:53
Will be part of the ix-icons release 2.0.1

**Comment by danielleroux** [comment] 2023-10-18 06:09
Not reproducible with latest version of ix-icons. If the issue is still a point, please reopen this issue and adapt the description.

**Closed by danielleroux** 2023-10-18 06:09 UTC
Labels: type: bug
