### ISSUE TITLE
Category Filter | Is there way to add free-text value for any category 

### ISSUE THREAD

**Issue by Jayesh26** [siemens/ix#1269] opened 2024-05-07 11:04 UTC
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/siemens/ix/blob/main/CONTRIBUTING.md).
- [X] I have not leaked any internal/restricted information like screenshots, videos, code snippets, links etc.

### Suggestion / feature request

![image](https://github.com/siemens/ix/assets/3745459/af54bd40-19cb-4c2a-a200-ad4743419341)

In above eg. we have added **"Name"** as category given free-text value (Name category options are empty []) 

We can see empty dropdown including static data, as we have given [] (empty) options why its showing ?

We are unbale to add few more category after free-text input value added for category.

**Comment by nuke-ellington** [comment] 2024-05-10 09:37
Hello @Jayesh26, thank you for your question. Can you please be more specific about the expected behaviour? Adding custom input to a category is possible. The dropdown is empty but shows the context the user is currently in (category name and operator).

**Comment by Jayesh26** [comment] 2024-05-16 08:20
Hi @nuke-ellington, Yes it shows the context but it does not allow me to add more filter category.
eg. Name: "testSearch" (free text search input) 
In above eg user has entered the value against the category "Name" and he wants to add more category then on clicking on "CategoryFiter" it will just show the values for previous category and wont let me add new category

**Comment by nuke-ellington** [comment] 2024-05-16 10:25
@Jayesh26 thank you for your message. Unfortunately it is not clear to me what the expected behaviour should be.
Could you please provide a step by step example?

E.g.:
- User selects category "Name"
- User types "testSearch"
- User presses "Enter"
- User selects category "Name"

**Comment by nuke-ellington** [comment] 2024-05-16 10:53
Thank you for the clarification @Jayesh26 . Unless the user presses "Enter" the text will remain in the input since the filter was not applied yet. They are still setting a filter for e.g. "Product". This is expected behavior so I will close the issue.

**Closed by nuke-ellington** 2024-05-16 10:53 UTC
Labels: type: enhancement, triage, wait for response

**Comment by Jayesh26** [comment] 2024-05-16 10:58
@nuke-ellington  True user has not pressed the "Enter" but he still wants to add some more filter and Category Filter is not allowing him to add after free-text value for last category. 
This can be a valid scenario in most of the cases where user want to add some free-text value as we are allowing him to add.
