### ISSUE TITLE
Clicking a entry in a dropdown, also triggers a click in the backdrop 

### ISSUE THREAD

**Issue by Stefei** [siemens/ix#1224] opened 2024-04-17 07:42 UTC
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/siemens/ix/blob/main/CONTRIBUTING.md).
- [X] I have not leaked any internal/restricted information like screenshots, videos, code snippets, links etc.

### What happened?

Clicking a entry in a dropdown, will also trigger a click in the backdrop. This is a problem for us, because we use a modal that closes if the user clicks outside of the modal bounds.

### What type of frontend framework are you seeing the problem on?

Angular, JavaScript

### Which version of iX do you use?

v2.1.0

### Code to produce this issue.

```shell
import { Component } from '@angular/core';

@Component({
  selector: 'app-example',
  template: `
    <div style="background-color:#ffffff; height: 1000px" onclick="console.log('backdrop clicked')">
    <ix-button #trigger>Open</ix-button>
    <ix-dropdown [ixDropdownTrigger]="trigger">
      <ix-dropdown-header label="Category"></ix-dropdown-header>
      <ix-dropdown-item label="Item 2"></ix-dropdown-item>
      <ix-dropdown-item label="Item 3"></ix-dropdown-item>
      <ix-dropdown-item label="Item 4"></ix-dropdown-item>
      <ix-divider></ix-divider>
      <ix-dropdown-item label="Item 5"></ix-dropdown-item>
    </ix-dropdown>
    </div>
  `,
})
export default class Dropdown {
}
```

**Comment by matthiashader** [comment] 2024-05-08 12:43
As this is a duplicate of #1229, this issue will be closed and further be discussed there.

**Closed by matthiashader** 2024-05-08 12:43 UTC
Labels: type: bug, type: duplicate
