### ISSUE TITLE
Modal dismiss handler unexpectedly gets called

### ISSUE THREAD

**Issue by TDaniel-evo** [siemens/ix#1510] opened 2024-10-09 13:35 UTC
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/siemens/ix/blob/main/CONTRIBUTING.md).
- [X] I have not leaked any internal/restricted information like screenshots, videos, code snippets, links etc.

### What happened?

Modal dismiss handler unexpectedly gets called.
When closing the modal, both close and dismiss handler gets called.
When dismissing the modal, the dismiss handler gets called twice.

See: https://stackblitz.com/edit/ne22aj-gs7xy7?file=src%2Fapp%2Fapp.component.ts

### What type of frontend framework are you seeing the problem on?

Angular

### Which version of iX do you use?

2.3.0

### Code to produce this issue.

```shell
private openModal() {
    from(
      this.modalService.open({
        content: DataCollectionComponent,
        size: '600',
        centered: true,
        data: 'Foo',
      })
    ).subscribe((instance) => {
      instance.onClose.on(() => {
        console.count('close modal');
      });
      instance.onDismiss.on(() => {
        console.count('dismiss modal'); // always gets called
      });
    });
  }
```

**Comment by danielleroux** [comment] 2024-10-09 14:14
@TDaniel-evo the issue is already be solved with pr https://github.com/siemens/ix/pull/1489
It will be part of the next release, I will close this issue here.

**Closed by danielleroux** 2024-10-09 14:14 UTC
Labels: triage
